app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('productos/',include(('applications.productos.urls' ,'productos'),namespace='productos')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    path('reses/',include(('applications.reses.urls' ,'reses'),namespace='reses')),
    path('caja/',include(('applications.caja.urls' ,'caja'),namespace='caja')),
    #path('carne/',include(('applications.carne.urls' ,'carne'),namespace='carne')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/productos/urls.py
from django.urls import path , include 
from .views import UnidadList,UnidadNew,UnidadUpdate ,ProductoNew,ProductoList,ProductoUpdate,CategoriaCreateView,CategoriaListView,MarcaCreateView,MarcaListView,CategoriaEditView,MarcaEditView,CortesListView
from django.contrib.auth import views as auth_views


urlpatterns = [
  
    path('unidades/',UnidadList.as_view(),name='lista_unidades'),
    path('unidades/unidadnew',UnidadNew.as_view(),name='crear_unidad'),
    path('unidades/unidadupdate/<int:pk>/',UnidadUpdate.as_view(),name='editar_unidad'),
 
    path('productos/',ProductoList.as_view(),name='lista_productos'),
    path('productos/new/',ProductoNew.as_view(),name='crear_producto'),
    path('productos/actualizar/<int:pk>',ProductoUpdate.as_view(),name='actualizar_producto'),

    path('productos/marcas/' ,MarcaListView.as_view(),name='lista_marcas'),
    path('productos/crearmarca/' ,MarcaCreateView.as_view(),name='crearmarca'),
    path('productos/editarmarca/<int:pk>' ,MarcaEditView.as_view(),name='editar_marca'),

    path('productos/categorias/' ,CategoriaListView.as_view(),name='lista_categorias'), 
    path('productos/crearcategoria/' ,CategoriaCreateView.as_view(),name='crearcategoria'),
    path('productos/editarcategoria/<int:pk>' ,CategoriaEditView.as_view(),name='editar_categoria'),

    path('productos/cortesdecarne/',CortesListView.as_view() ,name='lista_cortes' )
]

applications/bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    uc = UserForeignKey(auto_user_add=True,related_name='+')
    um = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract=True

applications/productos/models.py
from django.db import models
from applications.bases.models import ClaseModelo


class Unidad(ClaseModelo):
    nombre=models.CharField(max_length=10)
    def __str__(self):
         return self.nombre


MERCADERIA='mercaderia'
CARNE='carne'
TIPO=[
    (MERCADERIA,'mercaderia'),
    (CARNE,'carne'),
]


class Marca(ClaseModelo):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre

class Categoria(ClaseModelo):
    nombre = models.CharField(max_length=50)
    def __str__(self):
        return self.nombre
    

class Producto(ClaseModelo):
    nombre=models.CharField(max_length=40)
    descripcion=models.CharField(max_length=100 , blank=True ,null=True)
    codigo=models.CharField(max_length=30 ,unique=True)
    marca = models.ForeignKey(Marca, on_delete=models.CASCADE ,blank=True,null=True)
    categoria=models.ForeignKey(Categoria,on_delete=models.CASCADE ,blank=True,null=True)
    precioventa=models.FloatField()
    tipo = models.CharField(choices=TIPO, max_length=50 , blank=True ,null=True)
    unidad=models.ForeignKey(Unidad, on_delete=models.CASCADE)
    existencia=models.IntegerField(default=0)
    ultimacompra=models.DateField(blank=True , null=True)
    
    
    class Meta:
        verbose_name='Producto'
        verbose_name_plural='Productos'
        

    def __str__(self):
            return '{} - {}'.format(self.nombre,self.tipo)




  

applications/productos/forms.py
from .models import Unidad,Producto
from django import forms


class UnidadNewForm(forms.ModelForm):
    class Meta:
        model=Unidad
        fields=['nombre','estado']
        labels={'nombre':'Nombre'}
        #widget={'descripcion':forms.TextInput}

    def __init__(self, *args, **kwargs): #SE SOBRESCRIBE EL CONSTRUCTOR DEL FORMULARIO
        super().__init__(*args, **kwargs) #SE INVOCA EL CONSTRUCTOR
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })

class ProductoNewForm(forms.ModelForm):
    class Meta:
        model=Producto
        fields=['nombre','descripcion','codigo','tipo','precioventa','unidad','existencia','ultimacompra','estado','categoria','marca' ]
       
        widget={'descripcion':forms.TextInput, 'precioventa':forms.NumberInput(attrs={'required':True})}

    def __init__(self, *args, **kwargs): #SE SOBRESCRIBE EL CONSTRUCTOR DEL FORMULARIO
        super().__init__(*args, **kwargs) #SE INVOCA EL CONSTRUCTOR
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control',
            })
            self.fields['descripcion'].widget.attrs['required']=True
            self.fields['ultimacompra'].widget.attrs['readonly']=True
            self.fields['existencia'].widget.attrs['readonly']=True

    def clean(self):
        try:
            producto=Producto.objects.get(codigo=self.cleaned_data['codigo'])
            if not self.instance.pk:
                raise forms.ValidationError("El registro ya existe")
            elif self.instance.pk!=producto.pk:
                raise forms.ValidationError("Cambio no permitido")
        except Producto.DoesNotExist:
            pass
        return self.cleaned_data

applications/productos/views.py
from django.shortcuts import render
from .models import Producto ,Unidad,Categoria,Marca
# Create your views here.
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.views.generic import ListView ,UpdateView, CreateView ,TemplateView
from .forms import UnidadNewForm,ProductoNewForm
from django.urls import reverse_lazy
#,BodegaNewForm 
from django.http import HttpResponse, JsonResponse
from applications.bases.views import SinPrivilegios



class MarcaCreateView(CreateView):
    model = Marca
    template_name = "productos/crearmarca.html"
    fields=('nombre','estado')
    success_url=reverse_lazy('productos:lista_marcas')
    success_message='Marca creada exitosamente'


class MarcaListView(ListView):
    model = Marca
    context_object_name='obj'
    template_name = "productos/lista_marcas.html"


class MarcaEditView(UpdateView):
    model=Marca
    template_name = "productos/crearmarca.html"
    fields=('nombre','estado')
    context_object_name='obj'
    succes_message='Marca editada exitosamente'
    success_url=reverse_lazy('productos:lista_marcas')

class CategoriaCreateView(CreateView):
    model = Categoria
    template_name = "productos/crearcategoria.html"
    fields=('nombre','estado')
    success_url=reverse_lazy('productos:lista_categorias')
    success_message='Categoria creada exitosamente'

class CategoriaListView(ListView):
    model = Categoria
    context_object_name='obj'
    template_name = "productos/lista_categorias.html"


class CategoriaEditView(UpdateView):
    model = Categoria
    template_name = "productos/crearcategoria.html"
    context_object_name='obj'
    fields=('nombre','estado')
    success_url=reverse_lazy('productos:lista_categorias')
    success_message='Categoria editada exitosamente'



class MixinFormInvalid():
    def form_invalid(self , form):
        response=super().form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors , status=400)
        else:
            return response 



class UnidadList(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Unidad
    context_object_name='obj'
    template_name='productos/lista_unidades.html'
    login_url='bases:login'
    permission_required='producto.view_unidad'
    
class UnidadNew(SuccessMessageMixin,SinPrivilegios,CreateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='productos/crearunidad.html'
    success_url=reverse_lazy('productos:lista_unidades')
   
    permission_required='producto.add_unidad'
    success_message='Unidad creada exitosamente'
class UnidadUpdate(SuccessMessageMixin,SinPrivilegios,UpdateView):
    model=Unidad
    form_class=UnidadNewForm
    context_object_name='obj'
    template_name='productos/crearunidad.html'
    success_url=reverse_lazy('productos:lista_unidades')

    permission_required='producto.change_unidad'
    success_message='Unidad editada exitosamente'

    

class ProductoList(SuccessMessageMixin,SinPrivilegios,ListView): 
    model=Producto
    context_object_name='obj'
    template_name='productos/productos.html'
    login_url='bases:login'
    permission_required='producto.view_producto'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["productos"] = Producto.objects.filter(tipo='mercaderia',estado=True)
        return context

class CortesListView(SuccessMessageMixin,SinPrivilegios,ListView):
    model=Producto
    context_object_name='obj'
    template_name='productos/cortesdecarne.html'
    login_url='bases:login'
    permission_required='producto.view_producto'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["cortes"] = Producto.objects.filter(tipo='carne',estado=True)
        return context

       

    
class ProductoNew(SuccessMessageMixin,MixinFormInvalid,SinPrivilegios,CreateView): 
    model=Producto
    form_class=ProductoNewForm
    context_object_name='obj'
    template_name='productos/modalproducto.html'
    success_url=reverse_lazy('productos:lista_productos')
    login_url='bases:login'
    permission_required='producto.add_producto'
    success_message='Producto creado exitosamente'

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

    
    def get_context_data(self , **kwargs):
        context=super(ProductoNew , self).get_context_data(**kwargs)
        context['unidades']=Unidad.objects.filter(estado=True)
        context['categorias']=Categoria.objects.filter(estado=True)
        context['marcas']=Marca.objects.filter(estado=True)
        return context

class ProductoUpdate(SuccessMessageMixin, MixinFormInvalid,SinPrivilegios,UpdateView): 
    model=Producto
    form_class=ProductoNewForm
    context_object_name='obj'
    template_name='productos/modalproducto.html'
    success_url=reverse_lazy('productos:lista_productos')
    login_url='bases:login'
    permission_required='producto.change_producto'
    success_message='Producto editado exitosamente'
    #permission_required='vino.delete_vino'
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    def get_context_data(self, **kwargs):
        context=super(ProductoUpdate , self).get_context_data(**kwargs)
        pk = self.kwargs.get('pk')
        context['unidades']=Unidad.objects.filter(estado=True)
        context['categorias']=Categoria.objects.filter(estado=True)
        context['marcas']=Marca.objects.filter(estado=True)
        context["obj"] = Producto.objects.filter(pk=pk).first()
        return context

templates/productos/cortesdecarne.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE CORTES DE CARNE</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" onclick="return abrir_modal('{% url 'productos:crear_producto' %}')">Nuevo</a>
                      
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay cortes de carne
                 {% endif %}
                 <table class="table table-striped table-hover"
      id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
  
                 
                 >

                  <thead>
    <th data-sortable="true" data-field="nombre" >Nombre</th>
     <th data-sortable="true" data-field="codigo">Codigo</th>
                        <th data-sortable="true" >Precio</th>
                        <th data-sortable="true">Unidad</th>
                        <th data-sortable="true">Cantidad Vendida</th>
                      
                      
                    

                        <th data-sortable="true" >Ultimacompra</th>
                        <th class="all" >Editar</th>
                    </thead>
<tbody>
    
    {% for item in cortes  %}
    <tr>
     
        <td>{{item.nombre}}</td>
        <td>{{item.codigo}}</td>
    

        <td>{{item.precioventa}}</td>
        <td>{{item.unidad}}</td>
    
    <td>{{item.existencia}}</td>
   
       
       
      
        <td>
          
          {% if item.ultimacompra %}
          {{item.ultimacompra}}
          {% else %}
          No hay compras registradas
            
          {% endif %}
            </td>
      
        <td>
          <button type="submit" class="btn btn-warning btn-circle " role="button" onclick="return abrir_modal('{%url 'productos:actualizar_producto' item.id %} ')"><i class="far fa-edit"></i></button>
          
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
    
{% endblock js_page %}
    
    

templates/productos/crearcategoria.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'productos:editar_categoria' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'productos:crearcategoria' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Categoria
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">
                                 {{ form.nombre.label }}
                                {{ form.nombre }}
                            </div>
                            <div class="col">
                                {{form.estado.label}}
                                {{form.estado}}
                            </div>
                        
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/productos/crearmarca.html
<div class="modal-dialog modal-sm">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'productos:editar_marca' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'productos:crearmarca' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nueva {% endif %} Marca
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            <div class="col">
                                 {{ form.nombre.label }}
                                {{ form.nombre }}
                            </div>
                            <div class="col">
                                {{form.estado.label}}
                                {{form.estado}}
                            </div>
                        
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/productos/crearunidad.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Unidad
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-10">
                            <div class="input-group ">
                                <input type="text" name="nombre" maxlength="100" class="form-control m-1" required id="id_nombre" placeholder="Medida"
                                value="{% if obj %} {{ obj.nombre}} {% endif %}">
                            </div>
                        </div> 
                      
                        <div class="col-2">
                            <div class="form-group m-1">
                                <label for="id_estado">Estado</label>
                                <input type="checkbox" name="estado" class="form-control" id="id_estado"
                                {% if obj.estado %} checked 
                                {% endif %}  >
                            </div>
                        </div> 
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'productos:lista_unidades' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}

templates/productos/lista_categorias.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE CATEGORIAS</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                 
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay categorias registradas
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'productos:crearcategoria' %}')"><i class="far fa-calendar-plus"></i>Nueva</a></div>
                 <table data-toggle="table"
                 id="table"

                 data-pagination="true" 
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-AR"

                 >
                    <thead>
   <th data-sortable="true" data-field="id" >Id</th>
    <th data-sortable="true" data-field="nombre" >Nombre</th>

   

     <th data="numero" >Estado</i></th>
     
   
     <th class="all">Editar</th>
   
    
  
                    </thead>
<tbody>

    {% for item in obj  %}
    <tr>
      <td>{{item.id}}</td>

        <td>{{item.nombre}}</td>


        <td>
            
            {% if item.estado %}
                Activa
             {% else %}
             Inactiva   
            {% endif %}
                
        </td>
        
     
        <td>
          <button type="submit" class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'productos:editar_categoria' item.pk %}')"><i class="far fa-edit"></i></button>
     
             
            </td>
       
<!--modal de pagos del cliente-->
     
    
    
       </tr>  
       {% endfor %}
    
        
   
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}
{% block js_page %}

<script>

     </script>
{% endblock %}
    

templates/productos/lista_marcas.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE MARCAS</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      
                    </a>
                 
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay marcas registradas
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'productos:crearmarca' %}')"><i class="far fa-calendar-plus"></i>Nueva</a></div>
                 <table data-toggle="table"
                 id="table"

                 data-pagination="true" 
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-AR"

                 >
                    <thead>
   <th data-sortable="true" data-field="id" >Id</th>
    <th data-sortable="true" data-field="nombre" >Nombre</th>

   

     <th data="numero" >Estado</i></th>
     
   
     <th class="all">Editar</th>
   
    
  
                    </thead>
<tbody>

    {% for item in obj  %}
    <tr>
      <td>{{item.id}}</td>

        <td>{{item.nombre}}</td>


        <td>
            
            {% if item.estado %}
                Activa
             {% else %}
             Inactiva   
            {% endif %}
                
        </td>
        
     
        <td>
          <button type="submit" class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'productos:editar_marca' item.pk %}')"><i class="far fa-edit"></i></button>
     
             
            </td>
       
<!--modal de pagos del cliente-->
     
    
    
       </tr>  
       {% endfor %}
    
        
   
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}
{% block js_page %}

<script>

     </script>
{% endblock %}
    

templates/productos/lista_unidades.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE UNIDADES</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="{% url 'productos:crear_unidad' %}">Nueva</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay unidades
                 {% endif %}
                 <table class="table table-striped table-hover"
                 id="table"
                 data-toggle="table"
                 data-pagination="true"
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-NI"
                 
                 
                 >
                    <thead>
                  <th data-sortable="true" data-field="medida">Medida</th>
                  <th data-sortable="true">Estado</th>
  <th data-sortable="true">Usuario creador</th>
  <th>Ultima modificacion</th>
    <th class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item.nombre}}</td>
        <td>
          
          {% if item.estado is True %}
          Activo
          {% else %}
          Inactivo            
          {% endif %}
            
        </td>
        <td>{{item.uc}}</td>
        <th>{{item.fm}}
          {{item.um}}
        </th>
        <td>
            <a href="{% url 'productos:editar_unidad' item.id%}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
          
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
    
{% endblock js_page %}
    
    