app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('productos/',include(('applications.productos.urls' ,'productos'),namespace='productos')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    path('reses/',include(('applications.reses.urls' ,'reses'),namespace='reses')),
    path('caja/',include(('applications.caja.urls' ,'caja'),namespace='caja')),
    #path('carne/',include(('applications.carne.urls' ,'carne'),namespace='carne')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/reses/urls.py
from django.urls import path , include, re_path
from .views import (TropaNew,TropaUpdate,TropasList,\
                    AnimalNew,AnimalesList, \
                    ResesList,ResUpdate, \
                   VentaReses,ListaVentasReses,PagoVentaAjax,CrearPagoCliente,ListaPagosCliente)

urlpatterns = [
   
    path('tropas/' ,TropasList.as_view() , name='lista_tropas'),
    path('añadirtropa/' ,TropaNew.as_view() , name='crear_tropa'),
    path('editartropa/<int:pk>' ,TropaUpdate.as_view() , name='editar_tropa'),

    #path('animal/<int:pk>' ,AñadirAnimal.as_view() , name='animal'),
    path('animal/<int:pk>' ,AnimalNew , name='animal'),
    path('animales/<int:pk>' ,AnimalesList.as_view() , name='animales'),

     #path('registrares/' , ResCreateView.as_view() , name='registrares'),
    path('listareses/' , ResesList.as_view() , name='lista_reses'),
    path('updatereses/<int:pk>' ,ResUpdate.as_view() , name='editar_res'),
    #nueva vista para vender res (vista por funciones)

    path('nuevaventares/' ,VentaReses , name='nuevaventares'),
    path('editarventares/<int:id>' ,VentaReses , name='editarventares'),
    path('listaventas/',ListaVentasReses.as_view(),name='listaventas'),

    #prueba
    path('pagoventa/',PagoVentaAjax,name='pago_venta_ajax'),
    #path('pagocliente/<int:id>',PagoCliente,name='pago_cliente'),
    path('CrearPagoCliente/<int:id>',CrearPagoCliente.as_view(),name='crearpagocliente'),
    path('listapagos/<int:id>' ,ListaPagosCliente.as_view(),name='listapagos')
]

applications/ventas/urls.py
from django.urls import path , include

from .views import (ClienteNew ,ClienteList , ClienteEdit, \
                        EncVentaList , Ventas ,borrar_detalle_factura,\
                        ListaProductosTablaVenta )
from .reportes import imprimir_factura_recibo ,imprimir_factura_list


urlpatterns = [
    path('clientes/' , ClienteList.as_view() , name='lista_clientes'),
    path('clientes/new/' , ClienteNew.as_view() , name='crear_cliente'),
    path('clientes/<int:pk>' , ClienteEdit.as_view() , name='editar_cliente'),
    path('ventas/' , EncVentaList.as_view() , name='lista_ventas'),
    path('ventas/ventanew/' ,Ventas , name='nueva_venta'),
    path('ventas/ventaedit/<int:id>' ,Ventas , name='editar_venta'),
    #esta es la url del modal de productos
    path('ventas/buscarproductos/' ,ListaProductosTablaVenta  , name='tabla_productos'),
    #path('ventas/buscar_cortes/' ,ListaCortes , name='buscar_cortes'),
    path('ventas/imprimirecibo/<int:id>' , imprimir_factura_recibo ,name='imprimirecibo') ,
    path('ventas/imprimirventas/<str:f1>/<str:f2>/' , imprimir_factura_list , name='imprimirventas'),
    path('ventas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
]

applications/ventas/forms.py
from django import forms

from .models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model=Cliente
        fields=['nombre',
            'numero','direccion','estado']
        exclude = ['um','fm','fc']
        

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })
            self.fields['numero'].widget.attrs['requiered']=False
            self.fields['direccion'].widget.attrs['requiered']=False

applications/ventas/views.py
from django.shortcuts import render ,redirect
from .models import Cliente , FacturaDet ,FacturaEnc
from django.views import generic
from .forms import ClienteForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin ,PermissionRequiredMixin
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Q
from django.contrib import messages
from applications.productos.models import Producto
from django.contrib.auth.decorators import login_required, permission_required
from applications.bases.views import SinPrivilegios
from django.contrib.auth import authenticate
from .models import FacturaDet , FacturaEnc
#from applications.carne.models import Cortes
# Create your views here.

class VistaBaseCreate(SuccessMessageMixin,SinPrivilegios, \
    generic.CreateView):
    context_object_name = 'obj'
    success_message="Cliente creado exitosamente"

    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)

class VistaBaseEdit(SuccessMessageMixin,SinPrivilegios, \
    generic.UpdateView):
    context_object_name = 'obj'
    success_message="Cliente modificado exitosamente"

    def form_valid(self, form):
        #form.instance.um = self.request.user.id
        return super().form_valid(form)


class ClienteNew(VistaBaseCreate,SinPrivilegios):
    model=Cliente
    template_name="ventas/nuevo_cliente.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:lista_clientes")
    permission_required='ventas.add_cliente'
    success_message='Cliente creado exitosamente'
    
    def form_valid(self, form):
        form.instance.uc = self.request.user
        return super().form_valid(form)
    
class ClienteList(SinPrivilegios,generic.ListView):
    model = Cliente
    template_name = "ventas/lista_clientes.html"
    context_object_name = "obj"
    permission_required='ventas.view_cliente'

    def get_queryset(self):
        return super().get_queryset().filter(~Q(nombre='casual'))
    
  

class ClienteEdit(VistaBaseEdit,SinPrivilegios):
    model=Cliente
    template_name="ventas/nuevo_cliente.html"
    form_class=ClienteForm
    success_url= reverse_lazy("ventas:lista_clientes")
    permission_required='ventas.update_cliente'
    success_message='Cliente actualizado exitosamente'

    

#VISTA DE FUNCIONES
@login_required(login_url="/login/")
@permission_required("ventas.view_facturaenc",login_url="bases:sin_privilegios")

def Ventas(request , id=None):
    template_name='ventas/nueva_venta.html'
    encabezado={
        'fecha':datetime.today()
    }
    detalle={}
    
    clientes=Cliente.objects.filter(estado=True)
    

    if request.method=='GET':
        enc=FacturaEnc.objects.filter(pk=id).first()
        if not enc:
            encabezado={
                'id':0,
                'fecha':datetime.today(),
                'cliente':0,
                'sub_total':0.00 ,
                'descuento':0.00 ,
                'total': 0.00
        
            }
            detalle=None
        else:
            encabezado={
                'id':enc.id,
                'fecha':enc.fecha,
                'cliente':enc.cliente,
                'sub_total':enc.sub_total,
                'descuento':enc.descuento,
                'total':enc.total


            }
          



        detalle=FacturaDet.objects.filter(factura=enc)
        contexto = {"enc":encabezado,"det":detalle,"clientes":clientes}
        return render(request,template_name,contexto)

    if request.method=='POST':
        cliente=request.POST.get("enc_cliente")
      
        fecha=request.POST.get("enc_fecha")
        cli=Cliente.objects.get(pk=cliente)
      

        if not id:
            enc=FacturaEnc(
                cliente=cli,
                fecha=fecha,
                uc=request.user

            )
            if enc:
                enc.save()
                id=enc.id
        else:
            enc=FacturaEnc.objects.filter(pk=id).first()
            if enc:
                enc.cliente=cli
                enc.save()
        if not id:
            messages.error(request , "No se puede continuar ,Numero de factura no detectado")
            return redirect("ventas:ventas")

        codigo=request.POST.get("codigo")
        cantidad=request.POST.get("cantidad")
        precio=request.POST.get("precio")
        s_total=request.POST.get("sub_total_detalle")
        descuento=request.POST.get("descuento_detalle")
        total=request.POST.get("total")

        prod=Producto.objects.get(codigo=codigo)


        det=FacturaDet(
            factura=enc,
            producto=prod,
            cantidad=cantidad,
            precio=precio,
            sub_total=s_total,
            descuento=descuento,
            total=total,
            uc=request.user
            )
        if det:
            det.save()
        return redirect('ventas:editar_venta',id=id)



    return render(request , template_name, contexto)


class EncVentaList(SinPrivilegios,generic.ListView):
    model = FacturaEnc
    context_object_name='obj'
    template_name = "ventas/lista_ventas.html"
    permission_required='ventas.view_facturaenc'
    facs=FacturaEnc.objects.values('fecha')


def ListaProductosTablaVenta(request):
    template_name='ventas/tabla_productos.html'
    context={ 
        'productos':Producto.objects.all().order_by('tipo')  ##este order by devuelve primero los productos tipo carne y
        }                                                      #y luego la mercaderia
    return render(request,template_name,context)




############################################################################################################
def borrar_detalle_factura(request, id):
    template_name = "ventas/borrar_detalle.html"
    det = FacturaDet.objects.get(pk=id)
    
  
    #obteniendo la factura que se relaciona con este detalle
    id_enc=det.factura.id
    #obteniendo una instancia de esa factura
    enc=FacturaEnc.objects.get(pk=id_enc)
    
    #obteniendo el cliente de esa factura
    cliente=enc.cliente

    if request.method=="GET":
        context={"det":det}

    if request.method == "POST":
        usr = request.POST.get("usuario")
        pas = request.POST.get("pass")

        user =authenticate(username=usr,password=pas)

        if not user:
            return HttpResponse("Usuario o Clave Incorrecta")
        
        if not user.is_active:
            return HttpResponse("Usuario Inactivo")

        if user.is_superuser or user.has_perm("ventas.sup_caja_facturadet"):
            det.id = None
            det.cantidad = (-1 * det.cantidad)
            det.sub_total = (-1 * det.sub_total)
            det.descuento = (-1 * det.descuento)
            det.total = (-1 * det.total)
            det.save()
            
            cantidad_descontada=det.sub_total
            saldo=cliente.saldo

            if saldo!=float(0):
                
                cliente.saldo=saldo+cantidad_descontada
                cliente.save()
                print('------------------------se hizo el descuento')
            elif saldo==float(0):

                print('el saldo ya es 0',cliente.saldo)
            

            
            return HttpResponse("ok")

        return HttpResponse("Usuario no autorizado")
    
    return render(request,template_name,context)

'''

            #se obtiene el cliente que relacionado a la venta(o el que realizo la compra)
            cliente_id=enc.cliente.id
            #se obtiene la instancia de ese cliente
            cliente=Cliente.objects.get(pk=cliente_id)
            #se obtiene el saldo que tenia el cliente antes de realizar la compra
            saldo=cliente.saldo
            print('desde el borrado',enc.sub_total)
            #se actualiza su saldo con el monto de la compra que realizo
            cliente.saldo=saldo + enc.sub_total
            #se guarda la actualizacion en la base de datos
            cliente.save()'''

templates/ventas/borrar_detalle.html
<label class="text-danger">¿Anular Producto <b>{{det.producto.descripcion}}</b> de venta <b>{{det.factura.id}}</b>?</label>
<div>
    <div class="form-group">
        <label class="control-label">Usuario</label>
        <input type="text" id="usuario" class="form-control" required>
    </div>
    <div class="form-group">
        <label class="control-label">Contraseña</label>
        <input type="password" id="password" class="form-control" required>
    </div>
</div>

templates/ventas/imprimirecibo.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Recibo</title>
    <link rel="stylesheet" href="{% static 'base/css/recibo.css' %}">
    <style type="text/css">
       @page {
        size: letter;
        margin: 1cm;
    }

    .table td {
        text-align: center;
    }
    </style>
</head>
<body >
    <div class="col-md-1 col-sm-1 col-xs-1 col-xl-1">
        <center>
            <b class="text-center">Vinoteca</b><br> 
            <small>Direccion</small><br>
            
        </center>
        <small>
            <br>
            <b>Factura No.:</b>&nbsp;&nbsp;{{enc.id}}&nbsp;&nbsp;
            <b>Fecha Fact:</b>&nbsp;&nbsp;{{enc.fecha}}&nbsp;&nbsp; <br>
            <b>Cliente:</b>&nbsp;&nbsp; {{enc.cliente}}<br>
            <br><br>
        </small>
        <table class="table table-condensed table-sm" width="60%">
            <thead>
                <th>Código</th>
                <th  align='right'>Cant.</th>
                <th  align='right'>P. Unit.</th>
                <th  align='right'>Sub Total</th>
                <th  align='right'>Descuento</th>
                <th  align='right'>Total</th>
            </thead>
            <tbody>
                {% for obj in detalle %}
                <tr>
                    <td>{{obj.vino.codigo}}</td>
                    <td>{{obj.cantidad}}</td>
                    <td>{{obj.precio}}</td>
                    <td>{{obj.sub_total}}</td>
                    <td>{{obj.descuento}}</td>
                    <td>{{obj.total}}</td>
                </tr>
                <tr>
                    <td colspan="5">{{obj.producto}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="col-xs-1"></div>
        <div class="col-xs-11">
            <div class="pull-right">
            <table class="table-responsive dt-responsive nowrap">
                <thead>
                    <th colspan=2>Totales</th>
                </thead>
                <tbody>
                    <tr>
                        <td>Sub Total:</td> <td align='right'>{{enc.sub_total}}</td>
                    </tr>
                    <tr>
                        <td>Descuento</td> <td align='right'>{{enc.descuento}}</td>
                    </tr>
                    <tr>
                        <td>Total:</td> <td align='right'><b>{{enc.total}}</b></td>
                    </tr>
                </tbody>
            </table>
            </div>
        </div>
        <div class="row">
        <small class="pie">
            <br><br>
            <center>
                Creada por:  {{enc.uc}} - Fecha:  {{enc.fc}}
                <br>
               
            </center>
        </small>
        </div>
    </div>
</body>
</html>
<!--  <i>&copy; &reg; <b></b><br></i>  -->

templates/ventas/imprimirventas.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Listado de Ventas</title>

    <style type="text/css">
    @page {
        size: letter;
        margin: 1cm;
    }
    .table {
        width: 100%;
        max-width: 100%;
        margin-bottom: 5px;
        background-color: #fff;
    }
    .table th,
    .table td {
        padding: 5px;
        vertical-align: top;
        border-top: 1px solid #000;
        text-align: center;
    }
    .table thead th {
        vertical-align: bottom;
        border-bottom: 2px solid #000;
    }
    .table tbody + tbody {
        border-top: 2px solid #000;
    }
    .table .table {
        background-color: #fff;
    }
    .list-group {
        display: block;
        width: 100%;
        list-style: none;
        margin-top: 15px;
        margin-bottom: 15px;
    }
    .list-group p {
        width: 100%;
        height: 20px;
        line-height: 20px;
        list-style: none;
        font-size: 1.1em;
    }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <center>
                    
                    <h3>Reporte de ventas<br><small>Período: {{f1 | date:"d/m/Y"}} - {{f2 | date:"d/m/Y"}}</small></h3>
                </center>
            </div>

            <table class="table">
                <thead>
                    <tr>
                        <th>No. venta</th>
                        <th>Fecha</th>
                        <th>Cliente</th>
                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in enc %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.fecha | date:"d/m/Y"  }}</td>
                        <td>{{ item.cliente }}</td>
                        <td>{{ item.total }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</body>
</html>

templates/ventas/lista_clientes.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE CLIENTES</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
 
                    </a>
                 
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay pagos
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'ventas:crear_cliente' %}')"><i class="far fa-calendar-plus"></i>Nueva</a></div>
                 <table data-toggle="table"
                 id="table"

                 data-pagination="true" 
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-AR"

                 >
                    <thead>
   <th data-sortable="true" data-field="id" >id</th>
    <th data-sortable="true" data-field="nombre" >nombre</th>

   

     <th data="numero" >numero</i></th>

   
     <th class="all">Editar</th>
     <th  data-field="saldo" >saldo</th>
     <th   >Pagar</th>
     <th>Pagos</th>
    
  
                    </thead>
<tbody>

    {% for item in obj  %}
    <tr>
      <td>{{item.id}}</td>

        <td>{{item.nombre}}</td>


        <td>{{item.numero}}</td>
        
   
        <td>
          <button type="submit" class="btn btn-warning btn-circle" onclick="return abrir_modal('{% url 'ventas:editar_cliente' item.id %}')"><i class="far fa-edit"></i></button>
     
             
            </td>
         <td>{{item.saldo}}</td>
<!--modal de pagos del cliente-->
     
      
        <td ><a href="{% url 'reses:crearpagocliente' item.id %}" class="btn btn-success"><i class="fas fa-credit-card"></i></a>
        </td>  
    <td><a href="{%url 'reses:listapagos' item.id %}" class="btn btn-secondary"><i class="fas fa-list"></i></a></td>
       </tr>  
       {% endfor %}
    
        
   
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}
{% block js_page %}

<script>

     </script>
{% endblock %}
    

templates/ventas/lista_ventas.html
{% extends 'base.html' %}

{% block page_content %}
<div class="card shadow mb-4">
  <!-- Card Header - Dropdown -->
  <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
    <h6 class="m-0 font-weight-bold text-primary">Listado de ventas</h6>
  
  </div>
  <!-- Card Body -->
  <div class="card-body">
    <div class="row">
      <div class="col-md-4">
        <input type="text" class="form-class" name="f1" id="f1" readonly>
      </div>
      <div class="col-md-4">
        <input type="text" class="form-class" name="f2" id="f2" readonly>
      </div>
      <div class="col-md-4">
        <button class="btn btn-warning" type="button" id="btnPrint">Imprimir</button>
        
      </div>
    </div>
    <hr>

    
    {% if not obj %}
    <div class="alert alert-info">No Hay Ventas</div>
    {% endif %}
    <div class="buttons-toolbar">
        <a class="btn btn-success" href="{% url 'ventas:nueva_venta' %}"><i cass="far fa-calendar-plus"></i> Nuevo</a>
    </div>

    <table 
    id="table"
    data-toggle="table"
    data-pagination="true"
    data-search="true"
    data-show-columns="true"
    data-show-toggle="true"
    data-show-fullscreen="true"
    data-toolbar=".buttons-toolbar"
    data-locale="es-NI"
  >
  <thead>
    <th data-sortable="true" data-field="id">No.</th>        
    <th data-sortable="true" data-field="nombres">Cliente</th>
    <th data-sortable="true" data-field="apellidos">Total</th>
    <th data-field="estado">Fecha</th>
    <th>Por</th>
    <th class="all">Editar</th>
  </thead>
  <tbody>
    {% for item in obj%}
    <tr>
      <td>{{ item.id }}</td>
      <td>{{ item.cliente }}</td>
      <td>{{ item.total }}</td>
      <td>{{item.fecha}}</td>
      <td>{{item.uc}}</td>
      <td>
        <a href="{% url 'ventas:editar_venta' item.id %}" i class="href btn btn-warning btn-circle">
            <i class="far fa-edit"></i>
        </a>
        <a class="btn btn-success btn-circle" href="{% url 'ventas:imprimirecibo' item.id %}" target="reportes"><i class="fas fa-print"></i></a>
      </td>
    </tr>
    {% endfor %}
  </tbody>


  </table>
  </div>
</div>
{% endblock %}
{% block js_page %}
<script>
$(function(){
  $("#f1, #f2").datetimepicker({
      format: 'Y-m-d',
      timepicker:false
  });

  $("#btnPrint").click(function(e){
    e.preventDefault();
    var f1,f2;
    f1 = $("#f1").val();
    f2 = $("#f2").val();
    if(f1=="" || f1==null){
      f1="2019-06-01";
    }
    if(f2=="" || f2==null){
      var d = new Date();
      var f2 = d.getFullYear() + "-" + (d.getMonth()+1) + "-" + d.getDate();
    }
    
    var url = "imprimirventas/" + f1 + "/" + f2;

    window.open(url,'ventas');
    
  });
});
</script>
{% endblock %}

templates/ventas/nuevo_cliente.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        {% if obj %}
        <form role="form" action="{% url 'ventas:editar_cliente' obj.pk %}" method="post"  class="form-inline">
        {% else %}
        <form role="form" action="{% url 'ventas:crear_cliente' %}" method="post"  class="form-inline">
        {% endif %}
            <div class="col-xl-12 col-md-12 mb-12">
                {% if obj %}
                <div class="card border-left-warning shadow h-100 py-2">
                {% else %}
                <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            {% if obj %} Editar {% else %} Nuevo {% endif %} Cliente
                        </div>
                        <div class="dropdown-divider"></div>
                        {% csrf_token %}
                        <div class="row">
                            {{ form.as_p }}
                        </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" class="btn btn-success" onclick="return cerrar_modal()">
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                  
                    </div>
                </div>
                </div>
            </div>
        </form>
    </div>
</div> 

templates/ventas/tabla_productos.html
<div class="modal-dialog modal-lg">
    <div class="modal-content">
        <div class="col-xl-12 col-md-12 mb-12">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Buscar Producto
                        </div>
                        <div class="dropdown-divider"></div>
                        
                        <div class="row">
                                <table
                                id="tblMercaderias"
                                data-pagination="true"
                                data-search="true"
                                data-show-columns="true"
                                data-show-fullscreen="true"
                                data-locale="es-NI"
                                >
                                <thead>
                                  <th data-sortable="true" data-field="id">Id</th>        
                                  <th data-sortable="true" data-field="codigo">Código</th>
                                  <th data-sortable="true" data-field="codigo_barra">Barra</th>
                                  <th data-field="descripcion">Tipo</th>
                                  <th data-field="existencia">Existencia</th>
                                  <th data-field="precioventa">Precio</th>
                                  <th class="all">Acciones</th>
                                </thead>
                                <tbody>
                                  {% for item in productos%}
                                  <tr>
                                    <td>{{ item.id }}</td>
                                    <td>{{ item.nombre }}</td>
                                    <td>{{ item.codigo }}</td>
                                    <td>{{item.tipo}}</td>
                                    
                                    {% if item.tipo == 'mercaderia' %}
                                    <td>{{item.existencia}}</td>
                                    {% else %}
                                    <td>-</td>
                                    {% endif %}
                                        
                                  
                                    <td>{{item.precioventa}}</td>
                                    <td>
                                        
                                        {% if item.tipo == 'mercaderia' and item.existencia > 0 and item.estado %}
                                        <button class="btn btn-warning btn-circle" id="btnSelect" 
                                        onclick="seleccionarProducto({{item.id}},'{{item.codigo}}','{{item.descripcion}}','{{item.existencia}}','{{item.tipo}}',{{item.precioventa}} )"> <i class="far fa-hand-pointer"></i></button>
                                           
                                        </button>

                                        {% elif item.tipo == 'carne' and item.estado%}
                                        <button class="btn btn-warning btn-circle" id="btnSelect" 
                                        onclick="seleccionarProducto({{item.id}},'{{item.codigo}}','{{item.descripcion}}','{{item.existencia}}','{{item.tipo}}',{{item.precioventa}} )"> <i class="far fa-hand-pointer"></i></button>
                                              
                                           </button>

                                        {% endif %}
                                            

                                    
                                     
                               
                                    </td>
                                  </tr>
                                  {% endfor %}
                                </tbody>
                              </table>
                      
                            </div>
                        <div class="dropdown-divider"></div>
                        <div class="row">
                            <div class="col">
                                <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                                <button type="button" id="btnCancelar" class="btn btn-success">
                                        <!-- onclick="return cerrar_modal()" -->
                                        Cancelar
                                </button>
                            </div>
                        </div>
                    </div>
                
                    </div>
                </div>
            </div>
        </div>
    </div>
</div> 
{% block js_page %}
<script>
    $(function () {

        $("#btnCancelar").click(function(e){
            e.preventDefault();
            cerrar_modal();

        });
    });
    $('#tblMercaderias').bootstrapTable();

    function seleccionarProducto(id,codigo,descripcion,existencia,tipo,precioventa){
        console.log(tipo,codigo)
        $("#codigo").val(codigo);
        $("#descripcion").val(descripcion);
        $("#existencia").val(existencia);
        $("#precio").val(precioventa);
        $("#tipo").val(tipo);

        $("#btnCancelar").click();
        $("#codigo").select();
        $("#codigo").focus();

    }

</script>
{% endblock %}

<!--
  
-->