app/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('applications.bases.urls' ,'bases'),namespace='bases')),
    path('productos/',include(('applications.productos.urls' ,'productos'),namespace='productos')),
    path('compras/',include(('applications.compras.urls' ,'compras'),namespace='compras')),
    path('ventas/',include(('applications.ventas.urls' ,'ventas'),namespace='ventas')),
    path('apis/',include(('applications.apis.urls' ,'apis'),namespace='apis')),
    path('reses/',include(('applications.reses.urls' ,'reses'),namespace='reses')),
    path('caja/',include(('applications.caja.urls' ,'caja'),namespace='caja')),
    #path('carne/',include(('applications.carne.urls' ,'carne'),namespace='carne')),
    
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/reses/urls.py
from django.urls import path , include, re_path
from .views import (TropaNew,TropaUpdate,TropasList,\
                    AnimalNew,AnimalesList, \
                    ResesList,ResUpdate, \
                   VentaReses,ListaVentasReses,PagoVentaAjax,CrearPagoCliente,ListaPagosCliente)

urlpatterns = [
   
    path('tropas/' ,TropasList.as_view() , name='lista_tropas'),
    path('añadirtropa/' ,TropaNew.as_view() , name='crear_tropa'),
    path('editartropa/<int:pk>' ,TropaUpdate.as_view() , name='editar_tropa'),

    #path('animal/<int:pk>' ,AñadirAnimal.as_view() , name='animal'),
    path('animal/<int:pk>' ,AnimalNew , name='animal'),
    path('animales/<int:pk>' ,AnimalesList.as_view() , name='animales'),

     #path('registrares/' , ResCreateView.as_view() , name='registrares'),
    path('listareses/' , ResesList.as_view() , name='lista_reses'),
    path('updatereses/<int:pk>' ,ResUpdate.as_view() , name='editar_res'),
    #nueva vista para vender res (vista por funciones)

    path('nuevaventares/' ,VentaReses , name='nuevaventares'),
    path('editarventares/<int:id>' ,VentaReses , name='editarventares'),
    path('listaventas/',ListaVentasReses.as_view(),name='listaventas'),

    #prueba
    path('pagoventa/',PagoVentaAjax,name='pago_venta_ajax'),
    #path('pagocliente/<int:id>',PagoCliente,name='pago_cliente'),
    path('CrearPagoCliente/<int:id>',CrearPagoCliente.as_view(),name='crearpagocliente'),
    path('listapagos/<int:id>' ,ListaPagosCliente.as_view(),name='listapagos')
]

applications/ventas/urls.py
from django.urls import path , include

from .views import (ClienteNew ,ClienteList , ClienteEdit, \
                        EncVentaList , Ventas ,borrar_detalle_factura,\
                        ListaProductosTablaVenta )
from .reportes import imprimir_factura_recibo ,imprimir_factura_list


urlpatterns = [
    path('clientes/' , ClienteList.as_view() , name='lista_clientes'),
    path('clientes/new/' , ClienteNew.as_view() , name='crear_cliente'),
    path('clientes/<int:pk>' , ClienteEdit.as_view() , name='editar_cliente'),
    path('ventas/' , EncVentaList.as_view() , name='lista_ventas'),
    path('ventas/ventanew/' ,Ventas , name='nueva_venta'),
    path('ventas/ventaedit/<int:id>' ,Ventas , name='editar_venta'),
    #esta es la url del modal de productos
    path('ventas/buscarproductos/' ,ListaProductosTablaVenta  , name='tabla_productos'),
    #path('ventas/buscar_cortes/' ,ListaCortes , name='buscar_cortes'),
    path('ventas/imprimirecibo/<int:id>' , imprimir_factura_recibo ,name='imprimirecibo') ,
    path('ventas/imprimirventas/<str:f1>/<str:f2>/' , imprimir_factura_list , name='imprimirventas'),
    path('ventas/borrar-detalle/<int:id>',borrar_detalle_factura, name="factura_borrar_detalle"),
]

applications/bases/models.py
from django.db import models
from django.contrib.auth.models import User
from django_userforeignkey.models.fields import UserForeignKey


class ClaseModelo(models.Model):
    estado = models.BooleanField(default=True)
    fc = models.DateTimeField(auto_now_add=True)
    fm = models.DateTimeField(auto_now=True)
    # uc = models.ForeignKey(User, on_delete=models.CASCADE)
    # um = models.IntegerField(blank=True,null=True)
    uc = UserForeignKey(auto_user_add=True,related_name='+')
    um = UserForeignKey(auto_user=True,related_name='+')

    class Meta:
        abstract=True

applications/reses/models.py
from django.db import models
from applications.bases.models import ClaseModelo
from django.db.models.signals import post_save
from django.dispatch import receiver
from applications.ventas.models import Cliente
from django.db.models import Sum
# Create your models here.


#######################################################################
class Tropa(ClaseModelo):
    cant_animales = models.IntegerField()


    def __str__(self):
        return 'Tropa numero'+str(self.id)

##############################################################################    

class Animal(ClaseModelo):
    numero=models.IntegerField(default=0)
    ident=models.CharField(max_length=50,blank=True, null=True)
    tropa = models.ForeignKey(Tropa, on_delete=models.CASCADE)
    peso_animal=models.FloatField(default=0)

    #def save(self):
        #self.ident='animal:{}-tropa:{}'.format(self.id ,self.tropa)
     #   super(Animal , self).save()

    def __str__(self):
        #aqui deberia retornar el identificador del animal ?
        return 'Animal'+ str(self.numero) +'-'+ str(self.tropa)
    

#################################################################################################

class Res(ClaseModelo):
    animal = models.ForeignKey(Animal, on_delete=models.CASCADE)
    nombre=models.CharField(default='Res' ,max_length=20)
    peso= models.FloatField(max_length=7 , default=0)
    ingreso = models.DateTimeField(auto_now_add=True)
    vendida=models.BooleanField(default=False)
    
   

    class Meta:
        """Meta definition for MODELNAME."""

        verbose_name = 'Res'
        verbose_name_plural = 'Reses'

    def __str__(self):
        return self.nombre 

#################################viejo modelo de ventas###########################################################################

class EncVentaReses(ClaseModelo):
    fecha = models.DateTimeField(auto_now_add=True , blank=True ,null=True)
    total = models.FloatField(default=0.0)
    cliente=models.ForeignKey(Cliente, on_delete=models.CASCADE)
    #me sirve o no tener este campo??
    saldada=models.BooleanField(default=True) #porque la mayoria de las ventas seran de contado
    observacion = models.TextField(max_length=40,blank=True ,null=True)  
    #pagos = models.ForeignKey(Prueba,on_delete=models.CASCADE ,blank=True ,null=True) 

    def __str__(self):
        return str(self.id)
    
    class Meta:
        verbose_name = 'EncVentaReses'
        verbose_name_plural = 'EncsVentaReses'

class DetalleVentaRes(ClaseModelo):
    #venta -> venta a la cual pertenece un detalle de venta. en el modelo de arriba se llama enc
    venta=models.ForeignKey(EncVentaReses,on_delete=models.CASCADE,blank=True,null=True)
    res=models.ForeignKey(Res, on_delete=models.CASCADE)
    subtotal=models.FloatField(default=0)
    precio = models.FloatField(default=0.0,blank=True,null=True)

    class Meta:
        verbose_name = 'DetalleVentaRes'
        verbose_name_plural = 'DetallesVentaReses'
########################################################################################



class MedioPago(ClaseModelo):
    nombre=models.CharField(max_length=20)

    def __str__(self):
        return self.nombre
    class Meta:
        verbose_name='Medio de pago'
        verbose_name_plural='Medios de pago'

##################################################################################################        

class PagoReses(ClaseModelo):
    monto = models.FloatField(default=0.0)
    medio = models.ForeignKey(MedioPago, on_delete=models.CASCADE , blank=True ,null=True)
    venta = models.ForeignKey(EncVentaReses, on_delete=models.CASCADE,blank=True ,null=True)

    class Meta:
        

        verbose_name = 'pago_res'
        verbose_name_plural = 'pagos_reses'

    def __str__(self):
        
        return str(self.monto)
########################################################################################################
class PagoCliente(ClaseModelo):
    cliente=models.ForeignKey(Cliente,on_delete=models.CASCADE ,blank=True,null=True)
    monto = models.FloatField(default=0.0)
    medio = models.ForeignKey(MedioPago, on_delete=models.CASCADE , blank=True ,null=True)
    class Meta:
    
        verbose_name = 'pago_cliente'
        verbose_name_plural = 'pagos_clientes'

    def __str__(self):
        
        return str(self.monto)



#SECCION DE SIGNALS


@receiver(post_save, sender=Animal)
def CrearResesDeUnAnimal(sender, instance,**kwargs):
    tropa=instance.tropa            #ESTO DEBERIA ESTAR EN OTRO PROCESO
    id_animal=instance.id
   
    animal=Animal.objects.filter(id=id_animal).update(
        ident='animal{}-{}'.format(id_animal,tropa),
    )
   
    #print('desde el signal',animal) la variable animal devuelve 1 , esto quiere decir que el update fue exitoso
   
    #PROCESO PARA CREAR LAS DOS MEDIA RESES PERTENECIENTES  AL ANIMAL EN CUESTION
    reses=[]
    anm=Animal.objects.get(id=id_animal)
    for num in range(2):
        res =Res(
            animal=anm,             #aqui se deberia pasar el numero y no el id del animal
            nombre='res{}-animal{}'.format(num,anm.numero),
        )
        reses.append(res)
    Res.objects.bulk_create(reses)

#este signal es para cambiar el estado de una res luego de que se vende
@receiver(post_save, sender=DetalleVentaRes)
def post_venta_res(sender , instance,**kwargs):
    #venta a la cual pertence este detalle
    venta=instance.venta.id
    #obtengo la instancia de la res vendida
    id_res=instance.res.id
    res=Res.objects.get(pk=id_res)
    res.vendida=True
    res.save()


    enc=EncVentaReses.objects.filter(pk=venta).first()
    if enc:
        subtotal=DetalleVentaRes.objects.filter(venta=venta).aggregate(subtotal=Sum('subtotal')).get('subtotal',0.00)

        enc.total=subtotal

        enc.save()

        #actualizar saldo del cliente con una nueva venta. no comtempla el borrado
        cliente_id=enc.cliente.id
        cliente=Cliente.objects.get(pk=cliente_id)
        saldo_actual=cliente.saldo

        if subtotal>=0:
            cliente.saldo=saldo_actual + subtotal
            cliente.save()
            print('saldo del cliente positivo')
        elif subtotal<0:
            print('saldo cliente ngativo',cliente.saldo)

@receiver(post_save, sender=PagoCliente)       
def post_pago_clientes(sender , instance,**kwargs):
    cliente_pago=instance.cliente
    cliente=Cliente.objects.get(pk=cliente_pago.id)
    saldo_actual=cliente.saldo
    monto=instance.monto

    if saldo_actual>=monto:
        cliente.saldo=saldo_actual-monto
        cliente.save()
        print('nuevo saldo del cliente {} luego de descontar {}'.format(cliente.saldo,instance.monto))

    




    '''
    
class Prueba(models.Model):
    monto = models.CharField(max_length=50)
    medio = models.CharField(max_length=50)
    venta = models.ForeignKey(EncVentaReses, on_delete=models.CASCADE,blank=True ,null=True)

    def __str__(self):
        return self.monto + self.medio

    class Meta:
        verbose_name = 'prueba'
        verbose_name_plural = 'pruebas'



        
#este metodo luego de realizar una venta de reses , cambia el estado de la res vendida a True


#@receiver(post_save, sender=VentaReses)
def vender_reses(sender , instance,**kwargs):
    #obtener id de la res vendida
    id_res=instance.res.id
    #obtener la instancia de la res
    res=Res.objects.get(pk=id_res)
    #cambiar estado de la res
    res.vendida=True
    res.save()
    #aumentar monto de la venta al saldo del cliente
    id_cliente=instance.cliente.id

    cliente=Cliente.objects.get(pk=id_cliente)

    saldo_cliente=cliente.saldo
    print('desde el signal')
    precio_venta=instance.precio

    cliente.saldo=saldo_cliente+precio_venta

    #si se da de baja la venta con el estado=True
    if instance.estado is True:
        cliente.saldo=saldo_cliente-precio_venta

    cliente.save()




    @receiver(post_save, sender=PagoReses)
def pago_res(sender , instance,**kwargs):
    venta_id=instance.venta.id
    venta=EncVentaReses.objects.get(pk=venta_id)
    #cliente relacionado a la venta
    cliente=venta.cliente
    #obtener instancia de cliente
    instancia_cliente=Cliente.objects.get(nombre=cliente)
    
    #total de la venta
    
    if str(instance.medio)=='FIADO':
        monto_pago=float(instance.monto)
        saldo_cliente=instancia_cliente.saldo
        instancia_cliente.saldo=saldo_cliente+monto_pago
        print(monto_pago,instancia_cliente.saldo)
        instancia_cliente.save()
        print(instancia_cliente.saldo)

'''

applications/reses/forms.py
from django import forms

from .models import Animal,Res



class AnimalNewForm(forms.ModelForm):
    class Meta:
        model=Animal
        fields=(
            'tropa',
            'peso_animal'
        )

class ResEditForm(forms.ModelForm):
    class Meta:
        model=Res
        fields=('animal','nombre','peso','vendida')
        #METODO 1
         
    #METODO 2
    def __init__(self, *args, **kwargs):
        super(ResEditForm, self).__init__(*args, **kwargs)
        self.fields['animal'].widget.attrs['readonly']=True
        self.fields['nombre'].widget.attrs['readonly']=True
        self.fields['vendida'].widget.attrs['readonly']=True
        #self.fields['nombre'].widget.attrs['disabled']='disabled'

templates/reses/añadirtropa.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Cepa
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col-9" >
                            
                            <div style="margin: 5px;" class="input-group">
                               <label for="cant_animales" name="cant_animales">Cantidad de animales</label>
                             
                            </div>
                            {{form.cant_animales}}

                        </div>

                  <div class="col-3">
                      <label for="id_estado" name="estado">Estado</label>
                    {{form.estado}}
    
                </div>
                    </div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'reses:lista_tropas' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}
    
  {% block js_page %}
      
  {% endblock js_page %}
 

templates/reses/lista_pagos_cliente.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">LISTADO DE PAGOS DE {{cliente}}</h6>
                  <div class="dropdown no-arrow">
            
                    <a href="{% url 'ventas:lista_clientes' %}" class="btn btn-info" >Volver<i class="fas fa-undo"></i></a>
                 
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay cliente
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="dropdown-item" href="#" onclick="return abrir_modal('{% url 'ventas:crear_cliente' %}')"><i class="far fa-calendar-plus"></i>Nueva</a></div>
                 <table data-toggle="table"
                 id="table"

                 data-pagination="true" 
                 data-search="true"
                 data-show-columns="true"
                 data-show-toggle="true"
                 data-show-fullscreen="true"
                 data-toolbar=".buttons-toolbar"
                 data-locale="es-AR"

                 >
                    <thead>

    <th data-sortable="true" data-field="nombre" >Nombre</th>

   

     <th>Monto</th>
     <th>Medio de pago</th>
     <th>Fecha</th>
     <th>Usuario</th>
     <th>Cancelar</th>

  
    
  
                    </thead>
<tbody>

    {% for item in obj  %}
    <tr>
      <td>{{item.cliente}}</td>

        <td>{{item.monto}}</td>


        <td>{{item.medio}}</td>
        <td>{{item.fc}}</td>
        <td>{{item.uc}}</td>     
        <td><a href="#" class="btn btn-danger"><i class="fas fa-ban"></i></a></td>   

<!--modal de pagos del cliente-->
     
    
       </tr>  
       {% endfor %}
    
        
   
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}
{% block js_page %}

<script>

     </script>
{% endblock %}
    

templates/reses/lista_reses.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">REGISTRO DE RESES</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="">Nueva</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay registro de reses
                 {% endif %}
                 <div class="buttons-toolbar"> <a class="btn btn-success"  href="{% url 'reses:nuevaventares' %}" ><i class="fas fa-list" style="margin-right: 3px;"></i>Venta de reses</a></div>
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                        <th data-sortable="true" data-field="nombre">Nombre</th>
                        <th data-sortable="true" >Animal</th>
                        <th data-sortable="true" >Tropa</th>
                      <th>Peso</th>
                     
                      <th>Estado</th>
     
     <th  class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item}}</td>
        <td>{{item.animal.numero}}</td>
        <td>{{item.animal.tropa}}</td>
        <td>{{item.peso}}</td>
        
     
   
   
        <td>
          
          {% if  item.vendida %}
          Vendida
            {% else  %}
           No vendida
          {% endif %}
            
         
        </td>

        <td>
            <a href="{% url 'reses:editar_res' item.id %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    
    <!--

           <td>{{item.ingreso}} | {{item.uc}}</td>
        <td> {{item.fm}} |
          {{item.um}}
        </td>
    -->

templates/reses/lista_tropas.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Tropas registradas</h6>
                  <div class="dropdown no-arrow">
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                      <div class="dropdown-header">ACCIONES:</div>
                      <a class="dropdown-item" href="{% url 'reses:crear_tropa' %}">Nueva tropa</a>
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                 
                 {% if not obj %}
                     No hay tropas
                 {% endif %}
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                    
     <th data-field="numero" >Numero de tropa</i></th>
     <th >Cantidad de animales</th>
     <th  >Usuario creador</th>
     <th>Ultma modificacion</th>
    <th  class="all">Editar</th>
    <th>Añadir animal</th>
    <th>Lista animales</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item.id}}</td>
        <td>{{item.cant_animales}}</td>
        <td>{{item.uc}}</td>
        <td> {{item.fm}}
          {{item.um}}
        </td>
        
        <td>
            <a href="{% url 'reses:editar_tropa' item.pk %}" class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
        <td><a href="{% url 'reses:animal' item.pk %}" class="btn btn-success btn-circle " role="button" ><i class="fas fa-plus"></i></a></td>
       
        <td><a href="{% url 'reses:animales' item.pk %}" class="btn btn-info btn-circle " role="button" ><i class="fas fa-list"></i></a></td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

{% block js_page %}
<script>

     </script>
{% endblock js_page %}
    
    

templates/reses/listaresesvendidas.html
{% extends 'base.html' %}


{% block page_content %}

              <!-- Dropdown Card Example -->
              <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">REGISTRO DE VENTAS DE RESES</h6>
                  <div class="dropdown no-arrow">
                  <a href="" class="btn btn-google">Volver</a>
                    <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    
                    </a>
                    <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                   
                    
                    </div>
                  </div>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                  <a href="{% url 'reses:nuevaventares' %}" class="btn btn-success"><i class="fas fa-plus"></i> Nueva venta</a>
                 <table class="table table-striped table-hover"
                 
                 id="table"
      data-toggle="table"
      data-pagination="true"
      data-search="true"
      data-show-columns="true"
      data-show-toggle="true"
      data-show-fullscreen="true"
      data-toolbar=".buttons-toolbar"
      data-locale="es-NI"
                 
                 
                 
                 >
                    <thead>
                        <th data-sortable="true" >Venta</th>
                    
                      <th>Fecha</th>
     <th  >Total</th>
     <th>Usuario</th>
   
     <th  class="all">Editar</th>
                    </thead>
<tbody>
    
    {% for item in obj  %}
    <tr>
        <td>{{item.id}}</td>
  
        <td>{{item.fecha}}</td>
        <td>{{item.total}}</td>
        <td> {{item.uc}}
        </td>
       
        <td>
            <a href="{% url 'reses:editarventares' item.id %}"  class="btn btn-warning btn-circle " role="button" ><i class="far fa-edit"></i></a>
           
        </td>
    </tr>
        
    {% endfor %}
        
</tbody>

                 </table>
                     
                </div>
              </div>
    
{% endblock page_content %}

    
    

templates/reses/modal_pago_ajax.html
<h1>{{saludo}}</h1>

templates/reses/nueva_res.html
{% extends 'base.html' %}


{% block page_content %}

<form method="POST" class="form-inline">
    {% csrf_token %}
    <div class="col-xl-6 col-md-6 mb-6">
        {% if obj %}
        <div class="card border-left-warning shadow h-100 py-2">
        {% else %}
        <div class="card border-left-success shadow h-100 py-2">
        {% endif %}
            <div class="card-body">
            <div class="row no-gutters align-items-center">
                <div class="col mr-2">
                    <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                        {% if obj %} Editar {% else %} Nueva {% endif %} Res
                    </div>
                    <div class="dropdown-divider"></div>
                    {% csrf_token %}
<div class="row">
 {{form.as_p}}
</div>
                    <div class="dropdown-divider"></div>
                    <div class="row">
                        <div class="col">
                            <button type="submit" class="btn btn-danger"><span class="fa fa-save"></span> Guardar</button>
                            <a href="{% url 'reses:lista_reses' %}" class="btn btn-success"><span class="fa fa-undo"></span>Cancelar</a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </div>
</form>

  {% endblock page_content %}

templates/reses/nuevo_animal.html
{% extends 'base.html' %}


{% block page_content %}
<div class="col col-6"> 
<form action="" method="post">{% csrf_token %}
  <div class="col-md-8">
    <select name="tropa" id="id_tropa" class="form-control from-control-sm">
      
      {% if tropa %}
           
      {% for item in tropa  %}
      <option value="{{item.id}}">{{item}}</option>

      {% endfor %}
      <option value="0">-----------</option>
     
      {% endif %}
        
      
    </select>
</div>
<div class="col-md-8" style="margin-top: 10px;">
  <label for="peso_animal">Peso del animal</label>
  <input type="number" name="peso_animal" value="0" step="any" required="" id="id_peso_animal" class="form-control from-control-sm">

</div>
 <div class="col-md-8" style="margin-top: 10px;">
  <button class="btn btn-success" type="submit">crear</button>
  <a class="btn btn-google" href="{% url 'reses:lista_tropas' %} ">cancelar</a>
 </div>

</form>
</div>
{% endblock page_content %}
  <script>

  </script>